# Generated by Django 6.0.3 on 2026-04-05 03:55

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_identidad', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copia_cedula', models.BooleanField(default=False)),
                ('partida_nacimiento', models.BooleanField(default=False)),
                ('notas_certificadas_previas', models.BooleanField(default=False)),
                ('fotografias', models.BooleanField(default=False)),
                ('estatus', models.CharField(choices=[('SOLVENTE', 'Solvente'), ('INCOMPLETO', 'Incompleto')], default='INCOMPLETO', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='estudiantes.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalExpediente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('copia_cedula', models.BooleanField(default=False)),
                ('partida_nacimiento', models.BooleanField(default=False)),
                ('notas_certificadas_previas', models.BooleanField(default=False)),
                ('fotografias', models.BooleanField(default=False)),
                ('estatus', models.CharField(choices=[('SOLVENTE', 'Solvente'), ('INCOMPLETO', 'Incompleto')], default='INCOMPLETO', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estudiante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'historical expediente',
                'verbose_name_plural': 'historical expedientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
