# Generated by Django 6.0.3 on 2026-04-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_historicalestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='archivo_cedula',
            field=models.FileField(blank=True, null=True, upload_to='archivos/cedulas/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='archivo_fotos',
            field=models.FileField(blank=True, null=True, upload_to='archivos/fotos/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='archivo_notas',
            field=models.FileField(blank=True, null=True, upload_to='archivos/notas/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='archivo_partida',
            field=models.FileField(blank=True, null=True, upload_to='archivos/partidas/'),
        ),
        migrations.AddField(
            model_name='historicalexpediente',
            name='archivo_cedula',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpediente',
            name='archivo_fotos',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpediente',
            name='archivo_notas',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpediente',
            name='archivo_partida',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
