# Generated by Django 6.0.3 on 2026-04-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_expediente_archivo_cedula_expediente_archivo_fotos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='codigo_plan_estudio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='codigo_plantel',
            field=models.CharField(default='7409332', max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estado_nacimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='zona_educativa',
            field=models.CharField(default='U.E.N Liceo Nacional X', max_length=150),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='codigo_plan_estudio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='codigo_plantel',
            field=models.CharField(default='7409332', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='estado_nacimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='fecha_ingreso',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='zona_educativa',
            field=models.CharField(default='U.E.N Liceo Nacional X', max_length=150),
        ),
    ]
