# Generated by Django 6.0.3 on 2026-04-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_estudiante_codigo_plan_estudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='sexo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
