# Generated by Django 6.0.3 on 2026-04-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_historicalobservacionconductual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='email_representante',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Representante'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre_representante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Representante'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono_representante',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Representante'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='email_representante',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Representante'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='nombre_representante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Representante'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='telefono_representante',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Representante'),
        ),
    ]
