# Generated by Django 6.0.3 on 2026-04-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0008_estudiante_email_representante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='ano_cursando',
            field=models.IntegerField(choices=[(1, '1er Año'), (2, '2do Año'), (3, '3er Año'), (4, '4to Año'), (5, '5to Año'), (6, 'Egresado/Graduado')], default=1, verbose_name='Año que cursa'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='ano_cursando',
            field=models.IntegerField(choices=[(1, '1er Año'), (2, '2do Año'), (3, '3er Año'), (4, '4to Año'), (5, '5to Año'), (6, 'Egresado/Graduado')], default=1, verbose_name='Año que cursa'),
        ),
    ]
