# Generated by Django 6.0.3 on 2026-04-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0009_estudiante_ano_cursando_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='activo',
            field=models.BooleanField(default=True, help_text='False = registro inactivado (soft delete).'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_inactivacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el registro fue inactivado.', null=True),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='activo',
            field=models.BooleanField(default=True, help_text='False = registro inactivado (soft delete).'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='fecha_inactivacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el registro fue inactivado.', null=True),
        ),
    ]
