# Generated by Django 6.0.4 on 2026-05-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0010_soft_delete_activo_fecha_inactivacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='numero_expediente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Expediente'),
        ),
        migrations.AddField(
            model_name='historicalexpediente',
            name='numero_expediente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Expediente'),
        ),
    ]
