# Generated by Django 6.0.4 on 2026-06-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0011_expediente_numero_expediente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cedula_representante',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='C.I. del Representante'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='cedula_representante',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='C.I. del Representante'),
        ),
    ]
