# Generated by Django 6.0.4 on 2026-06-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0012_estudiante_cedula_representante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='seccion',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sección'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='seccion',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sección'),
        ),
    ]
