# Generated by Django 6.0.4 on 2026-06-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0013_estudiante_seccion_historicalestudiante_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='zona_educativa',
            field=models.CharField(default='U.E.N Colegio Apacuana', max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalestudiante',
            name='zona_educativa',
            field=models.CharField(default='U.E.N Colegio Apacuana', max_length=150),
        ),
    ]
