# Generated by Django 6.0.4 on 2026-06-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0014_alter_estudiante_zona_educativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='municipio_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio de Nacimiento'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pais_nacimiento',
            field=models.CharField(blank=True, default='Venezuela', max_length=100, null=True, verbose_name='País de Nacimiento'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='municipio_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio de Nacimiento'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='pais_nacimiento',
            field=models.CharField(blank=True, default='Venezuela', max_length=100, null=True, verbose_name='País de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='historicalestudiante',
            name='estado_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de Nacimiento'),
        ),
    ]
