# Generated by Django 6.0.4 on 2026-06-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0015_estudiante_municipio_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='ano_culminacion_1er_ano',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año Culminación 1er Año'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ano_culminacion_2do_ano',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año Culminación 2do Año'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ano_culminacion_3er_ano',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año Culminación 3er Año'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ano_culminacion_4to_ano',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año Culminación 4to Año'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ano_culminacion_5to_ano',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año Culminación 5to Año'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='mes_culminacion_1er_ano',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Mes Culminación 1er Año'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='mes_culminacion_2do_ano',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Mes Culminación 2do Año'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='mes_culminacion_3er_ano',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Mes Culminación 3er Año'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='mes_culminacion_4to_ano',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Mes Culminación 4to Año'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='mes_culminacion_5to_ano',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Mes Culminación 5to Año'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='ano_culminacion_1er_ano',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año Culminación 1er Año'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='ano_culminacion_2do_ano',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año Culminación 2do Año'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='ano_culminacion_3er_ano',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año Culminación 3er Año'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='ano_culminacion_4to_ano',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año Culminación 4to Año'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='ano_culminacion_5to_ano',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año Culminación 5to Año'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='mes_culminacion_1er_ano',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Mes Culminación 1er Año'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='mes_culminacion_2do_ano',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Mes Culminación 2do Año'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='mes_culminacion_3er_ano',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Mes Culminación 3er Año'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='mes_culminacion_4to_ano',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Mes Culminación 4to Año'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='mes_culminacion_5to_ano',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Mes Culminación 5to Año'),
        ),
    ]
