# Generated by Django 6.0.4 on 2026-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudiantes", "0016_estudiante_ano_culminacion_1er_ano_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="codigo_plantel",
            field=models.CharField(default="OD24061508", max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalestudiante",
            name="codigo_plantel",
            field=models.CharField(default="OD24061508", max_length=50),
        ),
    ]
