# Generated by Django 6.0.4 on 2026-07-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0018_alter_estudiante_ano_cursando_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='ano_cursando',
            field=models.IntegerField(choices=[(1, '1er Año'), (2, '2do Año'), (3, '3er Año'), (4, '4to Año'), (5, '5to Año'), (6, 'Egresado/Graduado')], default=1, verbose_name='Grado/Año que cursa'),
        ),
        migrations.AlterField(
            model_name='historicalestudiante',
            name='ano_cursando',
            field=models.IntegerField(choices=[(1, '1er Año'), (2, '2do Año'), (3, '3er Año'), (4, '4to Año'), (5, '5to Año'), (6, 'Egresado/Graduado')], default=1, verbose_name='Grado/Año que cursa'),
        ),
    ]
