# Generated by Django 6.0.4 on 2026-07-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0019_hard_delete_purge_inactivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='activo',
            field=models.BooleanField(default=True, help_text='Obsoleto: el borrado de estudiantes es físico y definitivo.'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_inactivacion',
            field=models.DateTimeField(blank=True, help_text='Obsoleto.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalestudiante',
            name='activo',
            field=models.BooleanField(default=True, help_text='Obsoleto: el borrado de estudiantes es físico y definitivo.'),
        ),
        migrations.AlterField(
            model_name='historicalestudiante',
            name='fecha_inactivacion',
            field=models.DateTimeField(blank=True, help_text='Obsoleto.', null=True),
        ),
    ]
