import os
import sys
import django

# Add apps to sys.path so Django can load models
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from django.db import connection

def run_sql():
    with connection.cursor() as cursor:
        print("Verifying and fixing PostgreSQL database schema...")
        
        # 1. Add columns to docentes_temaclase
        try:
            cursor.execute('ALTER TABLE "docentes_temaclase" ADD COLUMN IF NOT EXISTS "activo" boolean DEFAULT true NOT NULL;')
            print("- Checked 'activo' in docentes_temaclase")
        except Exception as e:
            print("Error adding activo to docentes_temaclase:", e)
            
        # 2. Add columns to docentes_materialapoyo
        try:
            cursor.execute('ALTER TABLE "docentes_materialapoyo" ADD COLUMN IF NOT EXISTS "activo" boolean DEFAULT true NOT NULL;')
            print("- Checked 'activo' in docentes_materialapoyo")
        except Exception as e:
            print("Error adding activo to docentes_materialapoyo:", e)
            
        try:
            cursor.execute('ALTER TABLE "docentes_materialapoyo" ADD COLUMN IF NOT EXISTS "subido_por_id" bigint NULL;')
            print("- Checked 'subido_por_id' in docentes_materialapoyo")
        except Exception as e:
            print("Error adding subido_por_id to docentes_materialapoyo:", e)
            
        # 3. Add columns to docentes_tareadocente
        try:
            cursor.execute('ALTER TABLE "docentes_tareadocente" ADD COLUMN IF NOT EXISTS "activa" boolean DEFAULT true NOT NULL;')
            print("- Checked 'activa' in docentes_tareadocente")
        except Exception as e:
            print("Error adding activa to docentes_tareadocente:", e)
            
        try:
            cursor.execute('ALTER TABLE "docentes_tareadocente" ADD COLUMN IF NOT EXISTS "creada_por_id" bigint NULL;')
            print("- Checked 'creada_por_id' in docentes_tareadocente")
        except Exception as e:
            print("Error adding creada_por_id to docentes_tareadocente:", e)
            
        # 4. Create docentes_registroasistencia table
        try:
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS "docentes_registroasistencia" (
                    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "fecha" date NOT NULL,
                    "estado" varchar(15) NOT NULL,
                    "observacion" text NOT NULL,
                    "metodo" varchar(10) NOT NULL,
                    "hora_registro" timestamp with time zone NOT NULL,
                    "hora_llegada" time NULL,
                    "estudiante_id" bigint NOT NULL,
                    "asignatura_id" bigint NOT NULL,
                    "periodo_id" bigint NOT NULL,
                    "seccion" varchar(5) NOT NULL,
                    "registrado_por_id" bigint NULL
                );
            ''')
            print("- Checked docentes_registroasistencia table")
        except Exception as e:
            print("Error creating docentes_registroasistencia:", e)

        # 5. Add foreign key constraints if needed
        for query in [
            'ALTER TABLE "docentes_materialapoyo" ADD CONSTRAINT "docentes_material_subido_por_id_edadf9f6_fk_usuarios_" FOREIGN KEY ("subido_por_id") REFERENCES "usuarios_usuario" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;',
            'ALTER TABLE "docentes_tareadocente" ADD CONSTRAINT "docentes_tareado_creada_por_id_50f3d84c_fk_usuarios_" FOREIGN KEY ("creada_por_id") REFERENCES "usuarios_usuario" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;',
            'ALTER TABLE "docentes_registroasistencia" ADD CONSTRAINT "docentes_registr_registrado_por_id_adfc6737_fk_usuarios_" FOREIGN KEY ("registrado_por_id") REFERENCES "usuarios_usuario" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;'
        ]:
            try:
                cursor.execute(query)
                print(f"- Checked constraint: {query[:60]}...")
            except Exception as e:
                # Will fail if constraint already exists, which is fine
                pass

        # 6. Add columns to usuarios_usuario and usuarios_historicalusuario
        try:
            cursor.execute('ALTER TABLE "usuarios_usuario" ADD COLUMN IF NOT EXISTS "nombre_completo" varchar(200) DEFAULT \'\' NOT NULL;')
            print("- Checked 'nombre_completo' in usuarios_usuario")
        except Exception as e:
            print("Error adding nombre_completo to usuarios_usuario:", e)
            
        try:
            cursor.execute('ALTER TABLE "usuarios_historicalusuario" ADD COLUMN IF NOT EXISTS "nombre_completo" varchar(200) DEFAULT \'\' NOT NULL;')
            print("- Checked 'nombre_completo' in usuarios_historicalusuario")
        except Exception as e:
            print("Error adding nombre_completo to usuarios_historicalusuario:", e)

if __name__ == '__main__':
    run_sql()
