# Generated by Django 6.0.3 on 2026-04-20 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('capacidad', models.IntegerField(default=30)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_grado', models.IntegerField(help_text='Año del grado académico (1, 2, 3...)')),
                ('seccion', models.CharField(help_text='Sección (A, B, C...)', max_length=5)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='inscripciones.periodoacademico')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'unique_together': {('ano_grado', 'seccion', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CLASE', 'Clase Académica'), ('RECESO', 'Receso'), ('ALMUERZO', 'Almuerzo'), ('OTRO', 'Otro Evento Especial')], default='CLASE', max_length=15)),
                ('dia_semana', models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('0', 'Domingo')], max_length=1)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('color_hex', models.CharField(default='#6366F1', help_text='Color para visualizar en el calendario', max_length=7)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscripciones.asignatura')),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.aula')),
                ('docente', models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='horarios.horario')),
            ],
            options={
                'verbose_name': 'Bloque de Horario',
                'verbose_name_plural': 'Bloques de Horario',
            },
        ),
    ]
