# Generated by Django 6.0.3 on 2026-04-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquehorario',
            name='aula_numero',
            field=models.CharField(blank=True, default='', help_text='Número de aula (solo dígitos).', max_length=10),
        ),
        migrations.AddField(
            model_name='bloquehorario',
            name='docente_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre del docente vinculado a la nómina.', max_length=255),
        ),
    ]
