# Generated by Django 6.0.3 on 2026-04-05 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloBachiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('numero_registro', models.CharField(help_text='Folio/Libro/Acta', max_length=50, unique=True)),
                ('codigo_qr_hash', models.CharField(max_length=255, unique=True)),
                ('ruta_pdf', models.FileField(blank=True, null=True, upload_to='titulos_generados/')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='titulo', to='estudiantes.estudiante')),
            ],
        ),
    ]
