# Generated by hand

from django.db import migrations

def update_subjects(apps, schema_editor):
    Asignatura = apps.get_model('inscripciones', 'Asignatura')
    Calificacion = apps.get_model('calificaciones', 'Calificacion')
    
    # 1. Eliminar calificaciones existentes (para evitar restricción PROTECT)
    Calificacion.objects.all().delete()
    
    # Intentar eliminar historial si simple_history está activo
    try:
        HistoricalCalificacion = apps.get_model('calificaciones', 'HistoricalCalificacion')
        HistoricalCalificacion.objects.all().delete()
    except Exception:
        pass

    # 2. Eliminar todas las asignaturas
    Asignatura.objects.all().delete()

    # 3. Crear las nuevas asignaturas
    materias_config = [
        {"nombre": "BIOLOGIA, AMBIENTE Y TECNOLOGIA", "abrv": "BAT"},
        {"nombre": "EDUCACIÓN FÍSICA", "abrv": "EDF"},
        {"nombre": "FÍSICA", "abrv": "FIS"},
        {"nombre": "GEOGRAFÍA, HISTORIA , Y SOBERANÍA NACIONAL", "abrv": "GHC"},
        {"nombre": "IDIOMAS", "abrv": "IDI"},
        {"nombre": "INNOVACIÓN TECNOLÓGICA Y PRODUCTIVA", "abrv": "INP"},
        {"nombre": "LENGUA Y LITERATURA", "abrv": "LYL"},
        {"nombre": "MATEMÁTICA", "abrv": "MAT"},
        {"nombre": "ORIENTACIÓN VOCACIONAL", "abrv": "ORV"},
        {"nombre": "QUÍMICA", "abrv": "QUI"},
    ]

    for ano in range(1, 6):
        for mat in materias_config:
            codigo = f"A{ano}-{mat['abrv']}"
            Asignatura.objects.create(
                codigo=codigo,
                nombre=mat['nombre'],
                ano_grado=ano
            )

def rollback_subjects(apps, schema_editor):
    Asignatura = apps.get_model('inscripciones', 'Asignatura')
    Asignatura.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
        ('calificaciones', '0004_alter_calificacion_tipo_and_more'),
    ]

    operations = [
        migrations.RunPython(update_subjects, reverse_code=rollback_subjects),
    ]
