# Generated by Django 6.0.4 on 2026-05-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0010_soft_delete_activo_fecha_inactivacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_riesgo_global', models.FloatField(default=0.0, help_text='Puntuación de 0 a 100')),
                ('materias_reprobadas', models.IntegerField(default=0)),
                ('faltas_documentales', models.IntegerField(default=0)),
                ('banderas_rojas', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_riesgo', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Registro de Riesgo',
                'verbose_name_plural': 'Registros de Riesgo',
                'ordering': ['-timestamp'],
            },
        ),
    ]
