# Generated by Django 6.0.3 on 2026-04-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonal',
            name='fecha_inactivacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el registro fue inactivado.', null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='fecha_inactivacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el registro fue inactivado.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpersonal',
            name='activo',
            field=models.BooleanField(default=True, help_text='False = registro inactivado (soft delete).'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='activo',
            field=models.BooleanField(default=True, help_text='False = registro inactivado (soft delete).'),
        ),
    ]
