# Generated by Django 6.0.3 on 2026-04-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_soft_delete_activo_fecha_inactivacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpersonal',
            name='salario_base',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='salario_base',
        ),
        migrations.AddField(
            model_name='historicalpersonal',
            name='esta_en_gestion_docentes',
            field=models.BooleanField(default=False, verbose_name='¿Está en gestión docente?'),
        ),
        migrations.AddField(
            model_name='personal',
            name='esta_en_gestion_docentes',
            field=models.BooleanField(default=False, verbose_name='¿Está en gestión docente?'),
        ),
    ]
