# Generated by Django 6.0.3 on 2026-04-25 02:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_remove_historicalpersonal_salario_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('es_activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(help_text='Descripción clara del gasto (Ej. Reparación de aire)', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('BS', 'Bolívares (Bs)'), ('USD', 'Dólares ($)'), ('EUR', 'Euros (€)')], default='BS', max_length=3)),
                ('tasa_cambio', models.DecimalField(decimal_places=2, default=1.0, help_text='Tasa BCV del día usada para cálculo', max_digits=12)),
                ('equivalente_bs', models.DecimalField(decimal_places=2, default=0.0, help_text='Total estandarizado a Bs', max_digits=14)),
                ('beneficiario_cedula_rif', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia en Bs'), ('PAGO_MOVIL', 'Pago Móvil'), ('ZELLE', 'Zelle'), ('BINANCE', 'Binance'), ('PAYPAL', 'PayPal'), ('DEPOSITO', 'Depósito Bancario'), ('OTRO', 'Otro')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha_pago', models.DateField()),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_servicios/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gastos', to='pagos.categoriaservicio')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalGastoServicio',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('razon', models.CharField(help_text='Descripción clara del gasto (Ej. Reparación de aire)', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('BS', 'Bolívares (Bs)'), ('USD', 'Dólares ($)'), ('EUR', 'Euros (€)')], default='BS', max_length=3)),
                ('tasa_cambio', models.DecimalField(decimal_places=2, default=1.0, help_text='Tasa BCV del día usada para cálculo', max_digits=12)),
                ('equivalente_bs', models.DecimalField(decimal_places=2, default=0.0, help_text='Total estandarizado a Bs', max_digits=14)),
                ('beneficiario_cedula_rif', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia en Bs'), ('PAGO_MOVIL', 'Pago Móvil'), ('ZELLE', 'Zelle'), ('BINANCE', 'Binance'), ('PAYPAL', 'PayPal'), ('DEPOSITO', 'Depósito Bancario'), ('OTRO', 'Otro')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha_pago', models.DateField()),
                ('comprobante', models.TextField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_registro', models.DateTimeField(blank=True, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aprobado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pagos.categoriaservicio')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical gasto servicio',
                'verbose_name_plural': 'historical gasto servicios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
