"""
WSGI config for config project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')

application = get_wsgi_application()
app = application

# Run migrations on startup to ensure all tables (including ia_analitica) exist
try:
    from django.core.management import call_command
    call_command('migrate', interactive=False)
except Exception as e:
    import logging
    logging.getLogger(__name__).error(f"Error running migrations on startup: {e}")

# Directly ensure the ia_analitica_registroriesgo table exists in case migration state is faked
try:
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS "ia_analitica_registroriesgo" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "nivel_riesgo_global" double precision NOT NULL,
                "materias_reprobadas" integer NOT NULL,
                "faltas_documentales" integer NOT NULL,
                "banderas_rojas" jsonb NOT NULL,
                "timestamp" timestamp with time zone NOT NULL,
                "estudiante_id" bigint NOT NULL CONSTRAINT "ia_analitica_registro_estudiante_id_fk_estudiant" REFERENCES "estudiantes_estudiante" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
            );
        ''')
        try:
            cursor.execute('CREATE INDEX IF NOT EXISTS "ia_analitica_registroriesgo_estudiante_id" ON "ia_analitica_registroriesgo" ("estudiante_id");')
        except Exception:
            pass
except Exception as e:
    import logging
    logging.getLogger(__name__).error(f"Error creating table ia_analitica_registroriesgo: {e}")



