# Generated by Django 6.0.3 on 2026-04-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol_historicalusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuario',
            name='nombre_completo',
            field=models.CharField(blank=True, default='', help_text='Nombre y apellido del operador para mostrar en el sistema.', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(blank=True, default='', help_text='Nombre y apellido del operador para mostrar en el sistema.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='rol',
            field=models.CharField(choices=[('PERSONAL', 'PERSONAL'), ('ADMINISTRATIVO', 'Administrativo'), ('COORDINADOR', 'Coordinador Académico'), ('DOCENTE', 'Docente'), ('AUDITOR', 'Auditor')], default='DOCENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('PERSONAL', 'PERSONAL'), ('ADMINISTRATIVO', 'Administrativo'), ('COORDINADOR', 'Coordinador Académico'), ('DOCENTE', 'Docente'), ('AUDITOR', 'Auditor')], default='DOCENTE', max_length=20),
        ),
    ]
