# Generated by Django 6.0.4 on 2026-05-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfiladministrativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='rol',
            field=models.CharField(choices=[('DESARROLLADOR', 'Desarrollador'), ('PERSONAL', 'ADMINISTRATIVO'), ('ADMINISTRATIVO', 'Directora'), ('COORDINADOR', 'Coordinador Académico'), ('DOCENTE', 'Docente'), ('AUDITOR', 'Auditor')], default='DOCENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('DESARROLLADOR', 'Desarrollador'), ('PERSONAL', 'ADMINISTRATIVO'), ('ADMINISTRATIVO', 'Directora'), ('COORDINADOR', 'Coordinador Académico'), ('DOCENTE', 'Docente'), ('AUDITOR', 'Auditor')], default='DOCENTE', max_length=20),
        ),
    ]
