# Generated by Django 6.0.4 on 2026-05-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_historicalusuario_rol_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalusuario',
            name='rol',
            field=models.CharField(choices=[('DESARROLLADOR', 'Desarrollador'), ('PERSONAL', 'ADMINISTRATIVO'), ('ADMINISTRATIVO', 'DIRECTORA'), ('COORDINADOR', 'Coordinador Académico'), ('DOCENTE', 'Docente'), ('AUDITOR', 'Auditor')], default='PERSONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('DESARROLLADOR', 'Desarrollador'), ('PERSONAL', 'ADMINISTRATIVO'), ('ADMINISTRATIVO', 'DIRECTORA'), ('COORDINADOR', 'Coordinador Académico'), ('DOCENTE', 'Docente'), ('AUDITOR', 'Auditor')], default='PERSONAL', max_length=20),
        ),
    ]
