# Generated by Django 6.0.3 on 2026-04-24 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(default='U', max_length=5)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('EXAMEN', 'Examen'), ('TAREA', 'Tarea'), ('PARTICIPACION', 'Participación'), ('PROYECTO', 'Proyecto'), ('PRACTICO', 'Trabajo Práctico'), ('OTRO', 'Otro')], default='EXAMEN', max_length=20)),
                ('ponderacion', models.DecimalField(decimal_places=2, help_text='Porcentaje de la nota final (1-100)', max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='inscripciones.asignatura')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='inscripciones.periodoacademico')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_grado', models.IntegerField()),
                ('seccion', models.CharField(max_length=5)),
                ('activa', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='inscripciones.asignatura')),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='inscripciones.periodoacademico')),
            ],
            options={
                'verbose_name': 'Asignación Docente',
                'verbose_name_plural': 'Asignaciones Docentes',
                'unique_together': {('docente', 'asignatura', 'periodo', 'seccion')},
            },
        ),
        migrations.CreateModel(
            name='NotaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(help_text='Nota en escala 0–20')),
                ('es_borrador', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='docentes.evaluacion')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_evaluaciones', to='inscripciones.inscripcion')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Evaluación',
                'verbose_name_plural': 'Notas de Evaluaciones',
                'unique_together': {('inscripcion', 'evaluacion')},
            },
        ),
        migrations.CreateModel(
            name='PeriodoCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(default='U', max_length=5)),
                ('cerrado', models.BooleanField(default=False)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='inscripciones.asignatura')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='inscripciones.periodoacademico')),
            ],
            options={
                'verbose_name': 'Cierre de Período',
                'verbose_name_plural': 'Cierres de Período',
                'unique_together': {('asignatura', 'periodo', 'seccion')},
            },
        ),
    ]
