# Generated by Django 6.0.3 on 2026-04-25 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('apellidos', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('estado_residencia', models.CharField(blank=True, choices=[('AMAZONAS', 'Amazonas'), ('ANZOATEGUI', 'Anzoátegui'), ('APURE', 'Apure'), ('ARAGUA', 'Aragua'), ('BARINAS', 'Barinas'), ('BOLIVAR', 'Bolívar'), ('CARABOBO', 'Carabobo'), ('COJEDES', 'Cojedes'), ('DELTA_AMACURO', 'Delta Amacuro'), ('DTTO_CAPITAL', 'Distrito Capital'), ('FALCON', 'Falcón'), ('GUARICO', 'Guárico'), ('LARA', 'Lara'), ('MERIDA', 'Mérida'), ('MIRANDA', 'Miranda'), ('MONAGAS', 'Monagas'), ('NUEVA_ESPARTA', 'Nueva Esparta'), ('PORTUGUESA', 'Portuguesa'), ('SUCRE', 'Sucre'), ('TACHIRA', 'Táchira'), ('TRUJILLO', 'Trujillo'), ('LA_GUAIRA', 'La Guaira'), ('YARACUY', 'Yaracuy'), ('ZULIA', 'Zulia')], default='', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Docente',
                'verbose_name_plural': 'Perfiles Docentes',
            },
        ),
    ]
