# Generated by Django 6.0.3 on 2026-04-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_perfildocente'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildocente',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula'),
        ),
    ]
