# Generated by Django 6.0.3 on 2026-04-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_perfildocente_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaevaluacion',
            name='asistencia',
            field=models.BooleanField(default=True, verbose_name='Asistencia'),
        ),
        migrations.AddField(
            model_name='notaevaluacion',
            name='observacion',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observación'),
        ),
    ]
