# Generated by Django 6.0.4 on 2026-06-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0004_notaevaluacion_asistencia_notaevaluacion_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildocente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='docentes/perfiles/', verbose_name='Foto de Perfil'),
        ),
    ]
