# Generated by Django 6.0.4 on 2026-06-06 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0005_perfildocente_foto_perfil'),
        ('inscripciones', '0002_update_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(default='U', max_length=5)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_clase', to='inscripciones.asignatura')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_creados', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_clase', to='inscripciones.periodoacademico')),
            ],
            options={
                'verbose_name': 'Tema de Clase',
                'verbose_name_plural': 'Temas de Clase',
                'ordering': ['fecha_programada', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TareaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instrucciones', models.TextField()),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evaluacion_vinculada', models.OneToOneField(blank=True, help_text='Opcional: Si esta tarea tiene calificación, se vincula a una Evaluación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarea_origen', to='docentes.evaluacion')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='docentes.temaclase')),
            ],
            options={
                'verbose_name': 'Tarea Asignada',
                'verbose_name_plural': 'Tareas Asignadas',
                'ordering': ['fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='MaterialApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='docentes/materiales/')),
                ('enlace', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='docentes.temaclase')),
            ],
            options={
                'verbose_name': 'Material de Apoyo',
                'verbose_name_plural': 'Materiales de Apoyo',
            },
        ),
    ]
