# Generated by Django 6.0.4 on 2026-06-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0006_temaclase_tareadocente_materialapoyo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondocente',
            name='aula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Aula'),
        ),
    ]
