# Generated by Django 6.0.3 on 2026-04-05 03:55

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('tipo', models.CharField(choices=[('PARCIAL', 'Parcial'), ('FINAL', 'Final'), ('REPARACION', 'Reparación')], default='FINAL', max_length=15)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCalificacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('tipo', models.CharField(choices=[('PARCIAL', 'Parcial'), ('FINAL', 'Final'), ('REPARACION', 'Reparación')], default='FINAL', max_length=15)),
                ('fecha_carga', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical calificacion',
                'verbose_name_plural': 'historical Calificaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
