# Generated by Django 6.0.3 on 2026-04-05 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscripciones.asignatura'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='inscripciones.inscripcion'),
        ),
        migrations.AddField(
            model_name='historicalcalificacion',
            name='asignatura',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inscripciones.asignatura'),
        ),
    ]
