# Generated by Django 6.0.3 on 2026-04-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='tipo',
            field=models.CharField(choices=[('L1', 'Primer Lapso'), ('L2', 'Segundo Lapso'), ('L3', 'Tercer Lapso'), ('DEF', 'Definitiva'), ('REP', 'Reparación')], default='DEF', max_length=15),
        ),
        migrations.AlterField(
            model_name='historicalcalificacion',
            name='tipo',
            field=models.CharField(choices=[('L1', 'Primer Lapso'), ('L2', 'Segundo Lapso'), ('L3', 'Tercer Lapso'), ('DEF', 'Definitiva'), ('REP', 'Reparación')], default='DEF', max_length=15),
        ),
    ]
