# Generated by Django 6.0.4 on 2026-05-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_alter_calificacion_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCertificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_normalizada', models.CharField(help_text='Cédula sin puntos, comas ni espacios', max_length=20, verbose_name='Cédula (normalizada)')),
                ('nombre_completo', models.CharField(max_length=250, verbose_name='Nombre completo')),
                ('nombres', models.CharField(blank=True, default='', max_length=150)),
                ('apellidos', models.CharField(blank=True, default='', max_length=150)),
                ('archivo_xlsx', models.FileField(upload_to='notas_certificadas/', verbose_name='Archivo Excel generado')),
                ('nombre_archivo_original', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cargado_por', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Nota Certificada',
                'verbose_name_plural': 'Notas Certificadas',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
