# Generated by Django 6.0.4 on 2026-06-12 22:46

import calificaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0005_nota_certificada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacertificada',
            name='archivo_xlsx',
            field=models.FileField(storage=calificaciones.models.select_raw_storage, upload_to='notas_certificadas/', verbose_name='Archivo Excel generado'),
        ),
    ]
