# Generated by Django 6.0.4 on 2026-06-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0006_alter_notacertificada_archivo_xlsx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notacertificada',
            old_name='archivo_xlsx',
            new_name='archivo_pdf',
        ),
    ]
