# Generated by Django 6.0.4 on 2026-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calificaciones", "0007_auto_20260612_1853"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notacertificada",
            name="archivo_pdf",
            field=models.FileField(
                upload_to="notas_certificadas/", verbose_name="Archivo PDF generado"
            ),
        ),
    ]
