# Generated by Django 6.0.3 on 2026-04-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAGO_MASIVO_OK', 'Pago Masivo Exitoso'), ('PAGO_MASIVO_ERROR', 'Pago Masivo con Error'), ('MODIFICACION', 'Modificación de Datos'), ('CREACION', 'Creación de Registro'), ('LOGIN', 'Inicio de Sesión'), ('OTRO', 'Otro Evento')], default='OTRO', max_length=30)),
                ('descripcion', models.TextField()),
                ('modulo', models.CharField(blank=True, default='', max_length=100)),
                ('usuario', models.CharField(blank=True, default='Sistema', max_length=150)),
                ('detalle_json', models.JSONField(blank=True, help_text='Datos adicionales estructurados del evento', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Evento de Auditoría',
                'verbose_name_plural': 'Eventos de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
