# Generated by Django 6.0.3 on 2026-04-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_nomina_aula_numero_evento_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoauditoria',
            name='impacto',
            field=models.CharField(blank=True, default='', help_text='Descripción del efecto del cambio en el sistema.', max_length=255),
        ),
        migrations.AddField(
            model_name='eventoauditoria',
            name='leido',
            field=models.BooleanField(default=False, help_text='Indica si la notificación fue vista en el dashboard.'),
        ),
        migrations.AddField(
            model_name='eventoauditoria',
            name='nivel_riesgo',
            field=models.CharField(choices=[('CRITICO', '🔴 Crítico'), ('MEDIO', '🟡 Medio'), ('INFORMATIVO', '🔵 Informativo')], default='INFORMATIVO', max_length=15),
        ),
        migrations.AddField(
            model_name='eventoauditoria',
            name='valor_anterior',
            field=models.JSONField(blank=True, help_text='Estado del registro ANTES del cambio.', null=True),
        ),
        migrations.AddField(
            model_name='eventoauditoria',
            name='valor_nuevo',
            field=models.JSONField(blank=True, help_text='Estado del registro DESPUÉS del cambio.', null=True),
        ),
        migrations.AlterField(
            model_name='eventoauditoria',
            name='detalle_json',
            field=models.JSONField(blank=True, help_text='Datos adicionales estructurados del evento.', null=True),
        ),
        migrations.AlterField(
            model_name='eventoauditoria',
            name='tipo',
            field=models.CharField(choices=[('PAGO_MASIVO_OK', 'Pago Masivo Exitoso'), ('PAGO_MASIVO_ERROR', 'Pago Masivo con Error'), ('PAGO_INDIVIDUAL', 'Pago Individual'), ('CREACION', 'Creación de Registro'), ('MODIFICACION', 'Modificación de Datos'), ('INACTIVACION', 'Inactivación de Registro'), ('BLOQUEO_DELETE', 'Intento de Eliminación Bloqueado'), ('LOGIN', 'Inicio de Sesión'), ('ACCESO_DENEGADO', 'Acceso Denegado'), ('IA_CONSULTA', 'Consulta al Asistente IA'), ('IA_INCONSISTENCIA', 'IA Detectó Inconsistencia'), ('OTRO', 'Otro Evento')], default='OTRO', max_length=30),
        ),
        migrations.AddIndex(
            model_name='eventoauditoria',
            index=models.Index(fields=['-timestamp'], name='auditoria_e_timesta_03ea11_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoauditoria',
            index=models.Index(fields=['nivel_riesgo', 'leido'], name='auditoria_e_nivel_r_da6084_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoauditoria',
            index=models.Index(fields=['tipo'], name='auditoria_e_tipo_623d71_idx'),
        ),
    ]
