# Generated by Django 6.0.3 on 2026-04-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_auditoria_semantica_nivel_riesgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('nivel_riesgo', models.CharField(choices=[('CRITICO', '🔴 Crítico'), ('ADVERTENCIA', '🟡 Advertencia'), ('INFORMATIVO', '🔵 Informativo')], default='INFORMATIVO', max_length=15)),
                ('modulo', models.CharField(blank=True, default='', max_length=100)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('agrupacion_hash', models.CharField(blank=True, db_index=True, default='', help_text='Identificador para agrupar alertas similares no leídas.', max_length=255)),
                ('conteo_agrupacion', models.IntegerField(default=1, help_text='Cantidad de veces que ocurrió este evento agrupado.')),
            ],
            options={
                'verbose_name': 'Notificación Operativa',
                'verbose_name_plural': 'Notificaciones Operativas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
