# Generated by Django 6.0.3 on 2026-04-25 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_notificacion_operativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoauditoria',
            name='tipo',
            field=models.CharField(choices=[('PAGO_MASIVO_OK', 'Pago Masivo Exitoso'), ('PAGO_MASIVO_ERROR', 'Pago Masivo con Error'), ('PAGO_INDIVIDUAL', 'Pago Individual'), ('CREACION', 'Creación de Registro'), ('MODIFICACION', 'Modificación de Datos'), ('INACTIVACION', 'Inactivación de Registro'), ('BLOQUEO_DELETE', 'Intento de Eliminación Bloqueado'), ('LOGIN', 'Inicio de Sesión'), ('ACCESO_DENEGADO', 'Acceso Denegado'), ('SOLICITUD_CONTROLADA', 'Acción Controlada por Solicitud'), ('SOLICITUD_APROBADA', 'Solicitud Aprobada por Administrativo'), ('SOLICITUD_RECHAZADA', 'Solicitud Rechazada por Administrativo'), ('IA_CONSULTA', 'Consulta al Asistente IA'), ('IA_INCONSISTENCIA', 'IA Detectó Inconsistencia'), ('OTRO', 'Otro Evento')], default='OTRO', max_length=30),
        ),
        migrations.CreateModel(
            name='SolicitudAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('eliminar_evaluaciones', 'Eliminar Evaluaciones'), ('restablecer_materias', 'Restablecer Materias de Docente'), ('eliminar_horarios', 'Eliminar Horarios'), ('eliminar_expedientes', 'Eliminar Expedientes'), ('otra_accion', 'Otra Acción')], default='otra_accion', max_length=50)),
                ('modulo', models.CharField(help_text='Módulo donde se quería actuar.', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción clara de qué quería hacer el Personal y sobre qué objeto.')),
                ('payload_json', models.JSONField(blank=True, help_text='Datos de la acción (IDs a eliminar, etc.) para ejecutar al aprobar.', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', '🟡 Pendiente'), ('APROBADA', '✅ Aprobada'), ('RECHAZADA', '❌ Rechazada'), ('EXPIRADA', '⏰ Expirada')], db_index=True, default='PENDIENTE', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha/hora a la que la solicitud expira automáticamente (48h desde creación).')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('comentario_admin', models.TextField(blank=True, default='', help_text='Comentario opcional del Administrativo al aprobar o rechazar.', max_length=1000)),
                ('leida_por_personal', models.BooleanField(default=False, help_text='Indica si el Personal ya vio la respuesta del Administrativo.')),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Administrativo que respondió')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Aprobación',
                'verbose_name_plural': 'Solicitudes de Aprobación',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['estado', '-fecha_solicitud'], name='auditoria_s_estado_339762_idx'), models.Index(fields=['solicitante', 'leida_por_personal'], name='auditoria_s_solicit_7ba5dd_idx')],
            },
        ),
    ]
