# Generated by Django 6.0.4 on 2026-05-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_alter_eventoauditoria_tipo_solicitudaprobacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevAuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('SQL_EXECUTE', 'Ejecución SQL'), ('SQL_MODIFY', 'Modificación SQL'), ('EXPORT_DB', 'Exportación de BD'), ('RESTORE_DB', 'Restauración de BD'), ('CLEAR_CACHE', 'Limpieza de Caché'), ('PURGE_AUDIT', 'Purga de Auditoría'), ('TEST_ERROR', 'Test de Excepción'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('VIEW_PANEL', 'Acceso al Panel'), ('EXPORT_LOGS', 'Exportación de Logs'), ('EXPORT_AUDIT', 'Exportación de Auditoría'), ('OTHER', 'Otra Acción')], default='OTHER', max_length=30)),
                ('usuario', models.CharField(default='Desconocido', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nivel_riesgo', models.CharField(choices=[('CRITICO', '🔴 Crítico'), ('ADVERTENCIA', '🟠 Advertencia'), ('INFORMATIVO', '🔵 Informativo')], default='INFORMATIVO', max_length=15)),
                ('query_sql', models.TextField(blank=True, default='')),
                ('rows_affected', models.IntegerField(blank=True, null=True)),
                ('execution_ms', models.FloatField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Log Técnico Desarrollador',
                'verbose_name_plural': 'Logs Técnicos Desarrollador',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='auditoria_d_timesta_e3b696_idx'), models.Index(fields=['accion', '-timestamp'], name='auditoria_d_accion_473e37_idx'), models.Index(fields=['nivel_riesgo'], name='auditoria_d_nivel_r_147a0e_idx')],
            },
        ),
    ]
